### ISSUE TITLE
Make transition from level end to next level smoother

### ISSUE THREAD

**Issue by Riduidel** [grzi/starlight-1961#44]
Currently, when I survive a level (not so often, in fact 😮), screen gets immediatly black.

Can you add some transition to a "you survived that level" screen ?

It would make experience smoother.

**Comment by grzi** [comment]
You said you have a black screen, can you confirm that it shows the next level number and a short text ? Or nothing on this transition screen ?

**Comment by Riduidel** [comment]
Yes, of course I have the next level number and the text.

But I would prefer some smoother transition (like an overlay or
something like that)

Le 28/11/2020 à 09:11, Jérémy Thulliez a écrit :

**Comment by grzi** [comment]
Issue fixed in the alpha 13
